<a href="https://colab.research.google.com/github/Evelyn199627/EERR/blob/main/Inventario_TTI.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [334]:
import pandas as pd
import numpy as np

In [335]:
df = pd.read_excel("/content/Inventario TTI - python.xlsx")

In [336]:
df.head()

,Articulo Solaut,Articulo TTI,Descripcion
0,1000,ACW 1000,ESCOBILLAS 6X6X15
1,1001,ACW 1001,"ESCOBILLAS 8,8X10X16 (PRECIO POR UNIDAD"
2,1002,ACW 1002,"ESCOBILLAS 8,X14X20"
3,8080,MCX 4932367168,4932430148 MECHA BROCA UNIDRE 4 X 85
4,8087,MCX 493239939,4932430157 MECHA BROCA UNIDRE 7X100

In [337]:
df['Articulo TTI '] = df['Articulo TTI '].astype(str).str.strip().str.upper()

In [338]:
df['Articulo Solaut '] = df['Articulo Solaut '].astype(str).str.strip().str.upper()

In [339]:
df[df["Articulo Solaut "] == "49252272"]

     Articulo Solaut  Articulo TTI               Descripcion
1439         49252272      49252272   DIAMOND GRIT BLADE 1PK

In [340]:
df[df["Articulo TTI "] == "24722"]

  Articulo Solaut  Articulo TTI                                  Descripcion
7            24722         24722    MECHA P/BROCA SDS PLUS 4 PLUS 17 X 210

In [341]:
df.shape

(2124, 3)

In [342]:
df.columns

Index(['Articulo Solaut ', 'Articulo TTI ', 'Descripcion '], dtype='object')

## SOLAUT

In [343]:
df_Solaut = pd.read_excel("/content/Inventario TTI.xlsx", sheet_name="SOLAUT ")

In [344]:
df_Solaut.columns

Index(['Fecha', 'Código', 'Cliente', 'Factura', 'Articulo Solaut ', 'Artículo',
       'Familia', 'Cant.', 'Precio L.', 'Desc. 1', 'Desc. 2', 'Desc. 3',
       'Desc. 4', 'Desc. 5', 'Desc. C.', 'Desc. P.', 'Tasa', 'Iva 10',
       'Iva 21', 'Neto', 'Total'],
      dtype='object')

In [345]:
df_Solaut.head()

,Fecha,Código,Cliente,Factura,Articulo Solaut,Artículo,Familia,Cant.,Precio L.,Desc. 1,...,Desc. 3,Desc. 4,Desc. 5,Desc. C.,Desc. P.,Tasa,Iva 10,Iva 21,Neto,Total
0,29/09/2025,44035,BELLINO EDUARDO JOSE,0057-A-00026481,48228462,CONSERVADORA XL DE 40QT PACKOUT,SIN DEF | SIN DEF,1,291537.88,0,...,0,0,0,0,0,21.0,0.0,55100.66,262384.09,317484.75
1,29/09/2025,44035,BELLINO EDUARDO JOSE,0057-A-00026481,48228460,ENFRIADOR COMPACTO PACKOUT,SIN DEF | SIN DEF,1,155712.99,0,...,0,0,0,0,0,21.0,0.0,29429.75,140141.69,169571.44
2,29/09/2025,33878,BULONERA TIGRE S.A,0188-A-00015422,AG750115A,4933419170 AMOLADORA 41/2 750W,SIN DEF | SIN DEF,2,86251.88,0,...,0,0,0,0,0,21.0,0.0,34414.50,163878.57,198293.07
3,29/09/2025,44497,"SIMOES ALVES CARLOS,CONTI ALEJANDRO",0057-A-00026482,49666249,1/2 DR 17MM STD IMPACT SOCKET,SIN DEF | SIN DEF,1,8557.57,0,...,0,0,0,0,0,21.0,0.0,1797.09,8557.57,10354.66
4,29/09/2025,44497,"SIMOES ALVES CARLOS,CONTI ALEJANDRO",0057-A-00026482,49666253,1/2 DR 21MM STD IMPACT SOCKET,SIN DEF | SIN DEF,1,9335.64,0,...,0,0,0,0,0,21.0,0.0,1960.48,9335.64,11296.12

In [346]:
df_Solaut.columns

Index(['Fecha', 'Código', 'Cliente', 'Factura', 'Articulo Solaut ', 'Artículo',
       'Familia', 'Cant.', 'Precio L.', 'Desc. 1', 'Desc. 2', 'Desc. 3',
       'Desc. 4', 'Desc. 5', 'Desc. C.', 'Desc. P.', 'Tasa', 'Iva 10',
       'Iva 21', 'Neto', 'Total'],
      dtype='object')

In [347]:
df_Solaut['Articulo Solaut '] = df_Solaut['Articulo Solaut '].astype(str).str.strip().str.upper()

In [348]:
dfsolautsum = (
    df_Solaut.groupby('Articulo Solaut ', as_index=False)[['Cant.', 'Neto']]
    .sum()
)

In [349]:
df_solautsum_filtrado = dfsolautsum[dfsolautsum['Cant.'] != 0]

In [350]:
df_solautsum_filtrado.columns

Index(['Articulo Solaut ', 'Cant.', 'Neto'], dtype='object')

In [351]:
df_solautsum_filtrado.sum()

Articulo Solaut     1016067581408012614200032142000641420013614200...
Cant.                                                           35780
Neto                                                    2444106838.72
dtype: object

In [352]:
df_solautsum_filtrado.shape

(676, 3)

In [353]:
df_final = pd.merge(
    df,
    dfsolautsum[['Articulo Solaut ', 'Cant.', "Neto"]],  # solo las columnas necesarias
    on="Articulo Solaut ",  # columna común en ambos archivos
    how="outer"
)

In [354]:
df[df["Articulo Solaut "] == "49252272"]

     Articulo Solaut  Articulo TTI               Descripcion
1439         49252272      49252272   DIAMOND GRIT BLADE 1PK

In [355]:
df_solautsum_filtrado[df_solautsum_filtrado["Articulo Solaut "] == "49252272"]

    Articulo Solaut   Cant.       Neto
534         49252272     19  407523.21

In [356]:
df_final.head()

,Articulo Solaut,Articulo TTI,Descripcion,Cant.,Neto
0,1000,ACW 1000,ESCOBILLAS 6X6X15,NaN,NaN
1,1001,ACW 1001,"ESCOBILLAS 8,8X10X16 (PRECIO POR UNIDAD",NaN,NaN
2,1002,ACW 1002,"ESCOBILLAS 8,X14X20",NaN,NaN
3,101606758,MCW 101606758,CARBONES,2.0,58076.26
4,14080126,MCW 14080126,INDUCIDO,1.0,41621.20

In [357]:
df_con_valorsolaut = df_final[df_final['Cant.'] != 0]

In [358]:
total = df_con_valorsolaut['Cant.'].sum()

In [359]:
total.shape

()

In [360]:
total

np.float64(35780.0)

In [361]:
df_final["Cant."] = df_final["Cant."] * -1

In [362]:
df_final.shape

(2132, 5)

In [363]:
df_final.to_excel('df_final.xlsx', index=False)

#FAMILIA DE ARTICULOS

In [364]:
df_familia = pd.read_excel("/content/INVENTARIO DATO .xlsx", sheet_name="OCTUBRE ")

In [365]:
df_familia.columns

Index(['Familia articulos ', 'Articulo TTI ', 'Descripcion ',
       'Transfer PRICE ', 'Costo según plan ', 'Landeo ',
       'Tasa despacho s/ despachante ', 'TOTAL FOB ', 'PRECIO VENTA ',
       'CANTIDADES INGRESADAS ', 'CANTIDADES VENDIDAS ',
       'CANTIDADES CIERRE OCTUBRE ', 'FOB REPORTE ', 'PROVEEDOR ',
       'PROVEEDOR .1', 'Unnamed: 15', 'Unnamed: 16'],
      dtype='object')

In [366]:
df_familia['Articulo TTI '] = df_familia['Articulo TTI '].astype(str).str.strip().str.upper()

In [367]:
df_familia["Articulo TTI "] = df_familia["Articulo TTI "].astype(str).str.strip().str.replace(r"\s+", "", regex=True)

In [368]:
df_articulos = pd.merge(
    df,
    df_familia[['Articulo TTI ', 'Familia articulos ']],  # solo las columnas necesarias
    on="Articulo TTI ",  # columna común en ambos archivos
    how="outer"
)

In [369]:
df_familia[df_familia["Articulo TTI "] == "24722"]

,Familia articulos,Articulo TTI,Descripcion,Transfer PRICE,Costo según plan,Landeo,Tasa despacho s/ despachante,TOTAL FOB,PRECIO VENTA,CANTIDADES INGRESADAS,CANTIDADES VENDIDAS,CANTIDADES CIERRE OCTUBRE,FOB REPORTE,PROVEEDOR,PROVEEDOR .1,Unnamed: 15,Unnamed: 16
7,MLK ACC MECHAS,24722,MECHA P/BROCA SDS PLUS 4 PLUS 17 X 210,0.0,0.0,0.0,NaN,0.0,16446.52,0.0,-10.0,30.0,3.4,TTI006,TTI006,NaN,NaN

In [370]:
df[df["Articulo TTI "] == "24722"]

  Articulo Solaut  Articulo TTI                                  Descripcion
7            24722         24722    MECHA P/BROCA SDS PLUS 4 PLUS 17 X 210

In [371]:
df_fliaart = pd.read_excel("/content/Inventario TTI - python.xlsx", sheet_name="Familia de articulos")

In [372]:
df_famarticulos = pd.merge(
    df,
    df_fliaart[['Articulo TTI ', 'Familia de articulos']],  # solo las columnas necesarias
    on="Articulo TTI ",  # columna común en ambos archivos
    how="outer"
)

In [373]:
df.columns

Index(['Articulo Solaut ', 'Articulo TTI ', 'Descripcion '], dtype='object')

# VALOR FOB

In [374]:
df_fob = pd.read_excel("/content/INVENTARIO DATO .xlsx", sheet_name="TRANSFER 2026 ")

In [375]:
df_fob['Articulo TTI '] = df_fob['Articulo TTI '].astype(str).str.strip().str.upper()

In [376]:
df["Articulo TTI "] = df["Articulo TTI "].astype(str).str.strip().str.replace(r"\s+", "", regex=True)
df_fob["Articulo TTI "] = df_fob["Articulo TTI "].astype(str).str.strip().str.replace(r"\s+", "", regex=True)

In [377]:
# Primer merge por Articulo TTI
merge_tti = df.merge(
    df_fob[['Articulo TTI ', '2026 Prelim Transfer Price']],
    on='Articulo TTI ',
    how='left'
)

In [378]:
df_fobfinal = pd.read_excel("/content/INVENTARIO DATO .xlsx", sheet_name="Valor FOB")

In [379]:
merge_tti.columns = merge_tti.columns.str.strip()
df_fobfinal.columns = df_fobfinal.columns.str.strip()

In [380]:
merge_tti["Articulo Solaut"] = merge_tti["Articulo Solaut"].astype(str).str.strip()
df_fobfinal["Articulo Solaut"] = df_fobfinal["Articulo Solaut"].astype(str).str.strip()

In [381]:
merge_tti.head()

,Articulo Solaut,Articulo TTI,Descripcion,2026 Prelim Transfer Price
0,1000,ACW1000,ESCOBILLAS 6X6X15,NaN
1,1001,ACW1001,"ESCOBILLAS 8,8X10X16 (PRECIO POR UNIDAD",NaN
2,1002,ACW1002,"ESCOBILLAS 8,X14X20",NaN
3,8080,MCX4932367168,4932430148 MECHA BROCA UNIDRE 4 X 85,NaN
4,8087,MCX493239939,4932430157 MECHA BROCA UNIDRE 7X100,NaN

In [382]:
merge_tti_vf = pd.merge(
    merge_tti,
    df_fobfinal[["Articulo Solaut", "Valor Fob U$S"]],
    on=["Articulo Solaut"],
    how='left'
)

In [383]:
merge_tti_vf.head()

,Articulo Solaut,Articulo TTI,Descripcion,2026 Prelim Transfer Price,Valor Fob U$S
0,1000,ACW1000,ESCOBILLAS 6X6X15,NaN,0.760000
1,1001,ACW1001,"ESCOBILLAS 8,8X10X16 (PRECIO POR UNIDAD",NaN,1.480000
2,1002,ACW1002,"ESCOBILLAS 8,X14X20",NaN,2.010000
3,8080,MCX4932367168,4932430148 MECHA BROCA UNIDRE 4 X 85,NaN,0.937637
4,8087,MCX493239939,4932430157 MECHA BROCA UNIDRE 7X100,NaN,1.078786

In [384]:
merge_tti_vf["Valor Fob U$S"] = np.where(
    merge_tti_vf["2026 Prelim Transfer Price"].notna(),
    np.nan,   # si tiene transfer price -> dejar vacío el FOB
    merge_tti_vf["Valor Fob U$S"]  # si no tiene transfer price -> conservar el FOB
)

In [385]:
merge_tti_vf.head()

,Articulo Solaut,Articulo TTI,Descripcion,2026 Prelim Transfer Price,Valor Fob U$S
0,1000,ACW1000,ESCOBILLAS 6X6X15,NaN,0.760000
1,1001,ACW1001,"ESCOBILLAS 8,8X10X16 (PRECIO POR UNIDAD",NaN,1.480000
2,1002,ACW1002,"ESCOBILLAS 8,X14X20",NaN,2.010000
3,8080,MCX4932367168,4932430148 MECHA BROCA UNIDRE 4 X 85,NaN,0.937637
4,8087,MCX493239939,4932430157 MECHA BROCA UNIDRE 7X100,NaN,1.078786

In [386]:
merge_tti_vf.columns

Index(['Articulo Solaut', 'Articulo TTI', 'Descripcion',
       '2026 Prelim Transfer Price', 'Valor Fob U$S'],
      dtype='object')

# UNION DE COLUMNAS

In [387]:
df.shape

(2124, 3)

In [388]:
df1 = df_final[['Articulo Solaut ', 'Cant.', "Neto"]]

In [389]:
df1["Cant."].sum()

np.float64(-35780.0)

In [390]:
df1.shape

(2132, 3)

In [391]:
df_invetariotti = (
    df
    .merge(df1, on='Articulo Solaut ', how='outer')
)

In [392]:
df_invetariotti["Cant."].sum()

np.float64(-35780.0)

In [393]:
df_articulos.columns

Index(['Articulo Solaut ', 'Articulo TTI ', 'Descripcion ',
       'Familia articulos '],
      dtype='object')

In [394]:
df2 = df_articulos[['Articulo TTI ', 'Familia articulos ']]

In [395]:
df2_clean = df2.drop_duplicates(subset='Articulo TTI ', keep='first')

In [396]:
df_invetariotti["Cant."].sum()

np.float64(-35780.0)

In [397]:
df.shape

(2124, 3)

In [398]:
df_invetariotti.shape

(2132, 5)

In [399]:
df_invetariotti['Articulo TTI '].isna().sum()
df2['Articulo TTI '].isna().sum()

np.int64(0)

In [400]:
df_invetariotti = (
    df_invetariotti
    .merge(df2_clean, on='Articulo TTI ', how='left')
)

In [401]:
df_invetariotti["Cant."].sum()

np.float64(-35780.0)

In [402]:
df_invetariotti.head()

,Articulo Solaut,Articulo TTI,Descripcion,Cant.,Neto,Familia articulos
0,1000,ACW1000,ESCOBILLAS 6X6X15,NaN,NaN,MLK REPUESTOS.
1,1001,ACW1001,"ESCOBILLAS 8,8X10X16 (PRECIO POR UNIDAD",NaN,NaN,MLK REPUESTOS.
2,1002,ACW1002,"ESCOBILLAS 8,X14X20",NaN,NaN,MLK REPUESTOS.
3,101606758,MCW101606758,CARBONES,-2.0,58076.26,MLK REPUESTOS.
4,14080126,MCW14080126,INDUCIDO,-1.0,41621.20,MLK REPUESTOS.

In [403]:
merge_tti_vf.columns

Index(['Articulo Solaut', 'Articulo TTI', 'Descripcion',
       '2026 Prelim Transfer Price', 'Valor Fob U$S'],
      dtype='object')

In [404]:
df3 = merge_tti_vf[['Articulo TTI', '2026 Prelim Transfer Price', "Valor Fob U$S"]]

In [405]:
df3_clean = df3.drop_duplicates(subset='Articulo TTI', keep='first')

In [406]:
df3_clean.columns

Index(['Articulo TTI', '2026 Prelim Transfer Price', 'Valor Fob U$S'], dtype='object')

In [407]:
df_invetariotti.columns

Index(['Articulo Solaut ', 'Articulo TTI ', 'Descripcion ', 'Cant.', 'Neto',
       'Familia articulos '],
      dtype='object')

In [408]:
df_invetariotti.columns = df_invetariotti.columns.str.strip()
df3_clean.columns = df3_clean.columns.str.strip()

In [409]:
df_invetariotti = (
    df_invetariotti
    .merge(df3_clean, on='Articulo TTI', how='left')
)

In [410]:
df4 = df_famarticulos[['Articulo TTI ', 'Familia de articulos']]

In [411]:
df4.columns = df4.columns.str.strip()

In [412]:
df4_clean = df4.drop_duplicates(subset='Articulo TTI', keep='first')

In [413]:
df4_clean.columns

Index(['Articulo TTI', 'Familia de articulos'], dtype='object')

In [414]:
df_invetariotti = (
    df_invetariotti
    .merge(df4_clean, on='Articulo TTI', how='left')
)

In [415]:
df_invetariotti.columns

Index(['Articulo Solaut', 'Articulo TTI', 'Descripcion', 'Cant.', 'Neto',
       'Familia articulos', '2026 Prelim Transfer Price', 'Valor Fob U$S',
       'Familia de articulos'],
      dtype='object')

In [416]:
df_invetariotti["Familia de articulos"] = df_invetariotti.apply(
    lambda row: "Accesorios"
    if isinstance(row["Familia articulos"], str) and "MLK REPUESTOS" in row["Familia articulos"].upper()
    else row["Familia de articulos"],
    axis=1
)

In [417]:
df_invetariotti["Cant."].sum()

np.float64(-35780.0)

In [418]:
df_invetariotti["Costo Standard  Unitario en $"] = df_invetariotti['2026 Prelim Transfer Price'] * 1500 * 1.35

# Landeo - Derecho

In [419]:
df_landeo = pd.read_excel("/content/INVENTARIO DATO .xlsx", sheet_name="% IMPORTACION ")

In [420]:
df_landeo.columns

Index(['DESCRIPCION', '% DERECHO', '% IVA', 'Unnamed: 3'], dtype='object')

In [421]:
df_landeo.columns = df_landeo.columns.str.strip()

In [422]:
df_invetariotti = df_invetariotti.merge(
    df_landeo[["DESCRIPCION", "% DERECHO"]],
    left_on="Familia de articulos",
    right_on="DESCRIPCION",
    how="left"
)

In [423]:
df_invetariotti = df_invetariotti.drop(columns=["DESCRIPCION"])

In [424]:
df_invetariotti.columns

Index(['Articulo Solaut', 'Articulo TTI', 'Descripcion', 'Cant.', 'Neto',
       'Familia articulos', '2026 Prelim Transfer Price', 'Valor Fob U$S',
       'Familia de articulos', 'Costo Standard  Unitario en $', '% DERECHO'],
      dtype='object')

In [425]:
df_invetariotti["% DERECHO"] = df_invetariotti["% DERECHO"].fillna(0.20)

In [426]:
df_invetariotti.columns

Index(['Articulo Solaut', 'Articulo TTI', 'Descripcion', 'Cant.', 'Neto',
       'Familia articulos', '2026 Prelim Transfer Price', 'Valor Fob U$S',
       'Familia de articulos', 'Costo Standard  Unitario en $', '% DERECHO'],
      dtype='object')

In [427]:
df_invetariotti.columns

Index(['Articulo Solaut', 'Articulo TTI', 'Descripcion', 'Cant.', 'Neto',
       'Familia articulos', '2026 Prelim Transfer Price', 'Valor Fob U$S',
       'Familia de articulos', 'Costo Standard  Unitario en $', '% DERECHO'],
      dtype='object')

In [428]:
df_invetariotti["Landeo General"] = 0.1529

In [429]:
df_invetariotti.columns

Index(['Articulo Solaut', 'Articulo TTI', 'Descripcion', 'Cant.', 'Neto',
       'Familia articulos', '2026 Prelim Transfer Price', 'Valor Fob U$S',
       'Familia de articulos', 'Costo Standard  Unitario en $', '% DERECHO',
       'Landeo General'],
      dtype='object')

In [430]:
df_invetariotti["Total Landeo"] = df_invetariotti["% DERECHO"] + df_invetariotti["Landeo General"]

In [431]:
df5_clean = (
    df_invetariotti[['Articulo TTI', '% DERECHO']]
    .drop_duplicates(subset='Articulo TTI', keep='first')
)

# Borro la versión vieja de % DERECHO del DF base
df_inventariotti = df_invetariotti.drop(columns=['% DERECHO'])

# Hago el merge y traigo la columna limpia
df_inventariotti = df_inventariotti.merge(
    df5_clean,
    on='Articulo TTI',
    how='left'
)

In [432]:
df_invetariotti.columns

Index(['Articulo Solaut', 'Articulo TTI', 'Descripcion', 'Cant.', 'Neto',
       'Familia articulos', '2026 Prelim Transfer Price', 'Valor Fob U$S',
       'Familia de articulos', 'Costo Standard  Unitario en $', '% DERECHO',
       'Landeo General', 'Total Landeo'],
      dtype='object')

In [433]:
df5_clean.columns

Index(['Articulo TTI', '% DERECHO'], dtype='object')

# Venta

In [434]:
df_venta = pd.read_excel("/content/Inventario TTI.xlsx", sheet_name="SOLAUT ")

In [435]:
df_venta['Articulo Solaut '] = df_venta['Articulo Solaut '].astype(str).str.strip().str.upper()

In [436]:
df_venta.columns

Index(['Fecha', 'Código', 'Cliente', 'Factura', 'Articulo Solaut ', 'Artículo',
       'Familia', 'Cant.', 'Precio L.', 'Desc. 1', 'Desc. 2', 'Desc. 3',
       'Desc. 4', 'Desc. 5', 'Desc. C.', 'Desc. P.', 'Tasa', 'Iva 10',
       'Iva 21', 'Neto', 'Total'],
      dtype='object')

In [437]:
#df_venta = df_venta.groupby("Articulo Solaut ").agg(
#    Cantidad_Total=("Cant.", "sum"),
#    Neto_Total=("Neto", "sum")
#).reset_index()

In [438]:
df_venta.columns

Index(['Fecha', 'Código', 'Cliente', 'Factura', 'Articulo Solaut ', 'Artículo',
       'Familia', 'Cant.', 'Precio L.', 'Desc. 1', 'Desc. 2', 'Desc. 3',
       'Desc. 4', 'Desc. 5', 'Desc. C.', 'Desc. P.', 'Tasa', 'Iva 10',
       'Iva 21', 'Neto', 'Total'],
      dtype='object')

In [439]:
#df_venta[df_venta["Articulo Solaut "].duplicated()]

In [440]:
#df_invetariotti = pd.merge(
#    df_invetariotti,
#    df_venta[['Articulo Solaut ', 'Neto_Total']],  # solo las columnas necesarias
#    left_on="Articulo TTI ",  # columna común en ambos archivos
#    right_on="Articulo Solaut ",
#    how="left"
#)

In [441]:
#df_invetariotti[df_invetariotti["Articulo TTI "].duplicated()]

In [442]:
#df_invetariotti["Cant."].sum()

In [443]:
df_invetariotti.rename(columns={'Cant.': 'Ventas del mes'}, inplace=True)

In [444]:
df_invetariotti.rename(columns={'Neto': 'VENTA'}, inplace=True)

In [445]:
df_invetariotti.columns

Index(['Articulo Solaut', 'Articulo TTI', 'Descripcion', 'Ventas del mes',
       'VENTA', 'Familia articulos', '2026 Prelim Transfer Price',
       'Valor Fob U$S', 'Familia de articulos',
       'Costo Standard  Unitario en $', '% DERECHO', 'Landeo General',
       'Total Landeo'],
      dtype='object')

## Creacion de calculos

In [446]:
df_invetariotti["Costo con landeo Real"] = df_invetariotti["Total Landeo"] * df_invetariotti["2026 Prelim Transfer Price"]* 1500

In [447]:
df_invetariotti["Costo Real"] = df_invetariotti["Costo con landeo Real"] * df_invetariotti["Ventas del mes"]

In [448]:
df_invetariotti.columns

Index(['Articulo Solaut', 'Articulo TTI', 'Descripcion', 'Ventas del mes',
       'VENTA', 'Familia articulos', '2026 Prelim Transfer Price',
       'Valor Fob U$S', 'Familia de articulos',
       'Costo Standard  Unitario en $', '% DERECHO', 'Landeo General',
       'Total Landeo', 'Costo con landeo Real', 'Costo Real'],
      dtype='object')

In [449]:
df_invetariotti["Costo"] = df_invetariotti["Costo Standard  Unitario en $"] * df_invetariotti["Ventas del mes"]

In [450]:
df_invetariotti["Rentabilidad absoluta"] = df_invetariotti["VENTA"] - df_invetariotti["Costo Real"]

In [451]:
df_invetariotti["Rentabilidad %"] = (df_invetariotti["VENTA"] - df_invetariotti["Costo"])/df_invetariotti["VENTA"]

ZeroDivisionError: float division by zero

In [452]:
df_invetariotti.columns

Index(['Articulo Solaut', 'Articulo TTI', 'Descripcion', 'Ventas del mes',
       'VENTA', 'Familia articulos', '2026 Prelim Transfer Price',
       'Valor Fob U$S', 'Familia de articulos',
       'Costo Standard  Unitario en $', '% DERECHO', 'Landeo General',
       'Total Landeo', 'Costo con landeo Real', 'Costo Real', 'Costo',
       'Rentabilidad absoluta'],
      dtype='object')

In [453]:
df_invetariotti.to_excel('df_invetariottifina.xlsx', index=False)

In [454]:
df_invetariotti["Ventas del mes"].sum()

np.float64(-35780.0)

In [455]:
df_invetariotti["VENTA"].sum()

np.float64(2444155090.98)